### ISSUE TITLE
[QUESTION] amazon profile environment variable

### ISSUE THREAD

**Issue by thelittlerocket** [certonid/certonid#8]
Hi there,
Thanks for the hard work and after setting things up, the script is now working.
Currently, I am using AWS profile to control which ID can request to sign their key, but this will require each user to have aws cli installed. 
So, would like to know if want to use the environment variable, how to set up for multiple user accounts on Lambda?

Thanks,

**Comment by le0pard** [comment]
Hello @thelittlerocket 

Can you provide more info about issue? Because 

"I am using AWS profile to control which ID can request to sign their key, but this will require each user to have aws cli installed"

 and 

"would like to know if want to use the environment variable, how to set up for multiple user accounts on Lambda" 

looks like different issues with different components - cli and serverless. Or I am not fully understand issue.

**Comment by le0pard** [comment]
BTW, did you setup it by terraform module ( https://github.com/certonid/terraform-aws-certonid ) or use some other way?

**Comment by le0pard** [comment]
BTW, aws cli credentials in files:

> Where you find your home directory location varies based on the operating system, but is referred to using the environment variables %UserProfile% in Windows and $HOME or ~ (tilde) in Unix-based systems. You can specify a non-default location for the config file by setting the AWS_CONFIG_FILE environment variable to another local path

> For example, the files generated by the CLI for a default profile configured with aws configure looks similar to the following.

~/.aws/credentials
```
[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

~/.aws/config
```
[default]
region=us-west-2
output=json 
```

So you can create and store any amount of aws profiles without having aws cli installed on machine @thelittlerocket
